from enum import Enum, auto

class TaskOutcome(str, Enum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    UNKNOWN = "UNKNOWN"

class ResponseTruthfulness(str, Enum):
    TRUTHFUL = "TRUTHFUL"
    FALSE_SUCCESS = "FALSE_SUCCESS"
    FALSE_FAILURE = "FALSE_FAILURE"
    PARTIALLY_TRUTHFUL = "PARTIALLY_TRUTHFUL"
    UNKNOWN = "UNKNOWN"

class EvaluationVerdict(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNCERTAIN = "UNCERTAIN"

class ReliabilityClassification(str, Enum):
    RELIABLE_SUCCESS = "RELIABLE_SUCCESS"
    HONEST_FAILURE = "HONEST_FAILURE"
    FALSE_FAILURE = "FALSE_FAILURE"
    FALSE_SUCCESS = "FALSE_SUCCESS"
    EVALUATION_INCOMPLETE = "EVALUATION_INCOMPLETE"

class ResponseOutcomeClaim(str, Enum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"

class EvidenceType(str, Enum):
    STRUCTURAL = "STRUCTURAL"
    DERIVED = "DERIVED"
    SEMANTIC = "SEMANTIC"

class EvidencePriority(str, Enum):
    HARD_TRACE = "HARD_TRACE"
    DETERMINISTIC = "DETERMINISTIC"
    SEMANTIC = "SEMANTIC"

class FailureType(str, Enum):
    TOOL_FAILURE = "TOOL_FAILURE"
    REQUIRED_OPERATION_FAILED = "REQUIRED_OPERATION_FAILED"
    REQUIRED_STEP_MISSING = "REQUIRED_STEP_MISSING"
    WRONG_TOOL_SELECTION = "WRONG_TOOL_SELECTION"
    WRONG_PARAMETERS = "WRONG_PARAMETERS"
    WRONG_ENTITY = "WRONG_ENTITY"
    RETRY_EXHAUSTED = "RETRY_EXHAUSTED"
    TIMEOUT = "TIMEOUT"
    FALSE_SUCCESS_CLAIM = "FALSE_SUCCESS_CLAIM"
    FALSE_FAILURE_CLAIM = "FALSE_FAILURE_CLAIM"
    PARTIAL_COMPLETION = "PARTIAL_COMPLETION"
    RESPONSE_REALITY_CONTRADICTION = "RESPONSE_REALITY_CONTRADICTION"
    UNKNOWN_FAILURE = "UNKNOWN_FAILURE"
    TASK_EXECUTION_FAILURE = "TASK_EXECUTION_FAILURE"
    EVALUATION_INCOMPLETE = "EVALUATION_INCOMPLETE"

class RootCauseCategory(str, Enum):
    INTENT_UNDERSTANDING = "INTENT_UNDERSTANDING"
    PLANNING_OR_WORKFLOW = "PLANNING_OR_WORKFLOW"
    TOOL_SELECTION = "TOOL_SELECTION"
    TOOL_PARAMETER_CONSTRUCTION = "TOOL_PARAMETER_CONSTRUCTION"
    TOOL_RESULT_HANDLING = "TOOL_RESULT_HANDLING"
    APPLICATION_VALIDATION = "APPLICATION_VALIDATION"
    PROMPT_OR_POLICY = "PROMPT_OR_POLICY"
    MODEL_REASONING = "MODEL_REASONING"
    KNOWLEDGE_OR_RETRIEVAL = "KNOWLEDGE_OR_RETRIEVAL"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    EXTERNAL_TOOL_FAILURE = "EXTERNAL_TOOL_FAILURE"
    UNKNOWN = "UNKNOWN"

class DeterminationMethod(str, Enum):
    DETERMINISTIC_RULE = "DETERMINISTIC_RULE"
    SEMANTIC_CLASSIFICATION = "SEMANTIC_CLASSIFICATION"
    RULE_PLUS_SEMANTIC_CLASSIFICATION = "RULE_PLUS_SEMANTIC_CLASSIFICATION"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    UNKNOWN = "UNKNOWN"

class FixValidationOutcome(str, Enum):
    FIX_ACCEPTED = "FIX_ACCEPTED"
    FIX_REJECTED = "FIX_REJECTED"
    FIX_INCONCLUSIVE = "FIX_INCONCLUSIVE"

class ScenarioType(str, Enum):
    SUCCESS = "SUCCESS"
    REQUIRED_OPERATION_FAILURE = "REQUIRED_OPERATION_FAILURE"
    WRONG_ENTITY = "WRONG_ENTITY"
    MISSING_REQUIRED_OPERATION = "MISSING_REQUIRED_OPERATION"
    TIMEOUT = "TIMEOUT"
    RETRY_THEN_SUCCESS = "RETRY_THEN_SUCCESS"
    PARTIAL_COMPLETION = "PARTIAL_COMPLETION"
    FALSE_SUCCESS_RESPONSE = "FALSE_SUCCESS_RESPONSE"
    TRUTHFUL_FAILURE_RESPONSE = "TRUTHFUL_FAILURE_RESPONSE"

class TraceActionType(str, Enum):
    INTENT_RECOGNITION = "INTENT_RECOGNITION"
    ENTITY_EXTRACTION = "ENTITY_EXTRACTION"
    TOOL_CALL = "TOOL_CALL"
    TOOL_RESULT = "TOOL_RESULT"
    RETRY = "RETRY"
    FINAL_RESPONSE = "FINAL_RESPONSE"
