"""Initial Phase 1 schema

Revision ID: 199216cebd6b
Revises: 
Create Date: 2026-09-04 01:01:46.558135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199216cebd6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('success_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('required_intent', sa.String(), nullable=True),
    sa.Column('required_entities', sa.JSON(), nullable=False),
    sa.Column('required_operations', sa.JSON(), nullable=False),
    sa.Column('required_final_state', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_success_specifications_id'), 'success_specifications', ['id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('scenario_parameters', sa.JSON(), nullable=False),
    sa.Column('metadata_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('success_specification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['success_specification_id'], ['success_specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_test_cases_task_type'), 'test_cases', ['task_type'], unique=False)
    op.create_table('execution_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('trace_identifier', sa.String(), nullable=False),
    sa.Column('final_response', sa.String(), nullable=True),
    sa.Column('final_state', sa.JSON(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_traces_id'), 'execution_traces', ['id'], unique=False)
    op.create_index(op.f('ix_execution_traces_trace_identifier'), 'execution_traces', ['trace_identifier'], unique=True)
    op.create_table('trace_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_parameters', sa.JSON(), nullable=True),
    sa.Column('tool_result', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_information', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('entity_identifiers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['execution_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_steps_id'), 'trace_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_steps_id'), table_name='trace_steps')
    op.drop_table('trace_steps')
    op.drop_index(op.f('ix_execution_traces_trace_identifier'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_id'), table_name='execution_traces')
    op.drop_table('execution_traces')
    op.drop_index(op.f('ix_test_cases_task_type'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_success_specifications_id'), table_name='success_specifications')
    op.drop_table('success_specifications')
    # ### end Alembic commands ###
