"""Phase 2 success specifications

Revision ID: 3a79d0ee6124
Revises: 199216cebd6b
Create Date: 2026-09-04 01:19:18.771301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a79d0ee6124'
down_revision: Union[str, Sequence[str], None] = '199216cebd6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('success_specifications', sa.Column('test_specific_constraints', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('success_specifications', 'test_specific_constraints')
    # ### end Alembic commands ###
