"""Add TaskSuccessEvaluationModel

Revision ID: aef2102eb069
Revises: 3a79d0ee6124
Create Date: 2026-09-04 13:11:30.920992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef2102eb069'
down_revision: Union[str, Sequence[str], None] = '3a79d0ee6124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_success_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('task_outcome', sa.String(), nullable=False),
    sa.Column('determination_method', sa.String(), nullable=False),
    sa.Column('structured_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['execution_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_success_evaluations_id'), 'task_success_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_task_success_evaluations_trace_id'), 'task_success_evaluations', ['trace_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_success_evaluations_trace_id'), table_name='task_success_evaluations')
    op.drop_index(op.f('ix_task_success_evaluations_id'), table_name='task_success_evaluations')
    op.drop_table('task_success_evaluations')
    # ### end Alembic commands ###
