"""Add ResponseTruthfulnessEvaluationModel

Revision ID: fa7692a574c4
Revises: aef2102eb069
Create Date: 2026-09-04 14:41:45.735099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7692a574c4'
down_revision: Union[str, Sequence[str], None] = 'aef2102eb069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_truthfulness_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=False),
    sa.Column('task_success_evaluation_id', sa.Integer(), nullable=True),
    sa.Column('response_truthfulness', sa.String(), nullable=False),
    sa.Column('response_outcome_claim', sa.String(), nullable=False),
    sa.Column('material_claims', sa.JSON(), nullable=False),
    sa.Column('contradictions', sa.JSON(), nullable=False),
    sa.Column('unsupported_claims', sa.JSON(), nullable=False),
    sa.Column('reasoning_summary', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_success_evaluation_id'], ['task_success_evaluations.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['execution_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_truthfulness_evaluations_id'), 'response_truthfulness_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_response_truthfulness_evaluations_trace_id'), 'response_truthfulness_evaluations', ['trace_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_truthfulness_evaluations_trace_id'), table_name='response_truthfulness_evaluations')
    op.drop_index(op.f('ix_response_truthfulness_evaluations_id'), table_name='response_truthfulness_evaluations')
    op.drop_table('response_truthfulness_evaluations')
    # ### end Alembic commands ###
